# Generated by Django 5.2.5 on 2025-09-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField()),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
